### ISSUE TITLE
usercode in M2Doc template is doing a NullPointerException in IS-Designer 1.9

### ISSUE THREAD

**Issue by ErwanGitHub** [ObeoNetwork/InformationSystem#30]
The same template works fine with IS-Designer 1.8.

java.lang.NullPointerException
	at org.obeonetwork.m2doc.generator.M2DocEvaluator.insertUserContent(M2DocEvaluator.java:1307)
	at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseUserDoc(M2DocEvaluator.java:1261)
	at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseUserDoc(M2DocEvaluator.java:1)
	at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:160)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.obeonetwork.m2doc.generator.M2DocEvaluator.doSwitch(M2DocEvaluator.java:1216)
	at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseBlock(M2DocEvaluator.java:1425)
	at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseBlock(M2DocEvaluator.java:1)
	at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:199)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.obeonetwork.m2doc.generator.M2DocEvaluator.doSwitch(M2DocEvaluator.java:1216)
	at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseDocumentTemplate(M2DocEvaluator.java:287)
	at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseDocumentTemplate(M2DocEvaluator.java:1)
	at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:279)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
	at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
	at org.obeonetwork.m2doc.generator.M2DocEvaluator.doSwitch(M2DocEvaluator.java:1216)
	at org.obeonetwork.m2doc.generator.M2DocEvaluator.generate(M2DocEvaluator.java:276)
	at org.obeonetwork.m2doc.util.M2DocUtils.generate(M2DocUtils.java:694)
	at org.obeonetwork.m2doc.util.M2DocUtils.generate(M2DocUtils.java:652)
	at org.obeonetwork.m2doc.genconf.GenconfUtils.generate(GenconfUtils.java:497)
	at org.obeonetwork.m2doc.genconf.GenconfUtils.generate(GenconfUtils.java:420)
	at org.obeonetwork.m2doc.genconf.editor.command.GenerateHandler$GenerateJob.runInWorkspace(GenerateHandler.java:86)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

[mpd_template.docx](https://github.com/ObeoNetwork/InformationSystem/files/3193697/mpd_template.docx)

**Comment by sthibaudeau** [comment]
Bug confirmed.

I created a ticket on M2Doc project
https://github.com/ObeoNetwork/M2Doc/issues/346

**Comment by sthibaudeau** [comment]
a workaround with a modified template has been identified on ticket https://github.com/ObeoNetwork/M2Doc/issues/346
